# Generated by Django 2.0.7 on 2019-11-01 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0002_auto_20191101_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time',
            name='total_time',
            field=models.FloatField(default=0.0),
        ),
    ]
